
name : push
on : [ push ]

jobs :

  Fast :
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-latest ]
        node-version : [ 12.x, 14.x, 16.x ]
    runs-on : ${{ matrix.os }}
    steps :
    - run : npm install wdeasync@delta w.process.tree.windows@delta bufferfromfile@delta
